
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "bou.ke/monkey"
  version = "1.0.1"

[[constraint]]
  name = "github.com/aead/siphash"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-socks"

[[constraint]]
  name = "github.com/btcsuite/goleveldb"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/websocket"

[[constraint]]
  name = "github.com/btcsuite/winsvc"
  version = "1.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jrick/logrotate"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kkdai/bstream"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.6"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
